[project]
name = "automl"
version = "1.0.0"
description = "AutoML SS25 Exam - Tabular"
authors = [{ name = "user", email = "user@user.com" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
  "pandas==2.3.0",
  "numpy==1.26.2",
  "scikit-learn==1.4.1.post1",
  "xgboost==3.0.2",
  "lightgbm==4.6.0",
  "catboost==1.2.8",
  "optuna==4.4.0",
  "pyarrow==20.0.0",
  "torch==2.7.1",
  "pytorch-tabnet==4.1.0"
]

classifiers = [
  'Intended Audience :: Science/Research',
  'Intended Audience :: Developers',
  'License :: OSI Approved :: BSD License',
  'Programming Language :: Python',
  'Topic :: Software Development',
  'Topic :: Scientific/Engineering',
  'Operating System :: POSIX',
  'Operating System :: Unix',
  'Operating System :: MacOS',
  'Programming Language :: Python :: 3',
]